name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup go 1.22.6
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.6

    - name: build
      run: go build -o my-web-app

    - name: test
      run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup go 1.22.6
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.6

    - name: run go cli lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.56.2

  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup docker build
      uses: docker/setup-buildx-action@v1

    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-web-app:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: docker-build-and-push

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: update tag in helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/my-web-app-chart/values.yaml

    - name: commit and push changes
      run: |
        git config --global user.email "abdulsamiabbasi1@gmail.com"
        git config --global user.name "abdulsami1"
        git add helm/my-web-app-chart/values.yaml
        git commit -m "update image tag in helm chart"
        git push
